language: generic

services:
 - docker

env:
 - DEPENDENCY_PACKAGES="libvala-dev valac meson"

install:
 - docker pull elementary/docker:juno-unstable
 - docker run -v "$PWD":/tmp/build-dir elementary/docker:juno-unstable /bin/sh -c "apt-get update && apt-get -y install $DEPENDENCY_PACKAGES && cd /tmp/build-dir && meson build && cd build && ninja"

script:
 - echo BUILDS PASSED
